import { useEffect, useMemo, useState } from "react";
import { BarChart3, Bot, CalendarDays, Download, List, Monitor, Sparkles, Tag, X } from "lucide-react";
import { CartesianGrid, Line, LineChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { COMPANY_COLORS, COMPANIES, KEYWORDS, TIME_SEGMENTS } from "./config";
import { sampleObservations } from "./data/sample";
import type { RankingObservation } from "./types";

type KeywordFilter = "TOP2 (통합)" | "비교 (통합)" | (typeof KEYWORDS)[number];
type DeviceFilter = "ALL" | "PC" | "MOBILE";
type TimeFilter = "ALL" | (typeof TIME_SEGMENTS)[number]["id"];
const keywordButtons: { value: KeywordFilter; label: string }[] = [
  { value: "TOP2 (통합)", label: "TOP2 (통합)" }, { value: "자동차보험", label: "자동차보험" }, { value: "다이렉트자동차보험", label: "다이렉트자동차보험" },
  { value: "비교 (통합)", label: "비교 (통합)" }, { value: "비교견적사이트", label: "비교견적사이트" }, { value: "자동차보험비교", label: "자동차보험비교" },
];

function kst(value: string) {
  const p = new Intl.DateTimeFormat("en-CA", { timeZone: "Asia/Seoul", year: "numeric", month: "2-digit", day: "2-digit", hour: "2-digit", hourCycle: "h23", weekday: "short" }).formatToParts(new Date(value)).reduce<Record<string,string>>((a, v) => ({ ...a, [v.type]: v.value }), {});
  return { date: `${p.year}-${p.month}-${p.day}`, month: `${p.year}-${p.month}`, hour: Number(p.hour), weekday: p.weekday };
}
function keywordsFor(value: KeywordFilter) { return value === "TOP2 (통합)" ? [KEYWORDS[0], KEYWORDS[1]] : value === "비교 (통합)" ? [KEYWORDS[2], KEYWORDS[3]] : [value]; }
function avg(rows: RankingObservation[]) { const a = rows.flatMap((r) => r.rank == null ? [] : [r.rank]); return a.length ? a.reduce((s,n) => s+n,0)/a.length : null; }
function availableMonths(rows: RankingObservation[]) { return [...new Set(rows.map(r=>kst(r.observedAt).month))].sort().slice(-3); }
function rank(value: number | null) { return value == null ? "-" : `${value.toFixed(1)}위`; }
function prevMonth(month: string) { const [y,m]=month.split("-").map(Number); const d=new Date(y,m-2,1); return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}`; }
function sortedCompanies(rows: RankingObservation[]) { return COMPANIES.map(company => ({ company, average: avg(rows.filter(r=>r.company===company)) })).filter(v=>v.average!=null).sort((a,b)=>a.average!-b.average!); }
function excel(filename:string, headers:string[], rows:(string|number)[][]) { const body=`<table><tr>${headers.map(v=>`<th>${v}</th>`).join("")}</tr>${rows.map(r=>`<tr>${r.map(v=>`<td>${v}</td>`).join("")}</tr>`).join("")}</table>`; const blob=new Blob([`<html><meta charset="utf-8">${body}</html>`],{type:"application/vnd.ms-excel"}); const a=document.createElement("a"); a.href=URL.createObjectURL(blob); a.download=filename; a.click(); URL.revokeObjectURL(a.href); }

export function App() {
  const [observations,setObservations]=useState<RankingObservation[]>(sampleObservations), [generatedAt,setGeneratedAt]=useState<string|null>(null);
  const [keyword,setKeyword]=useState<KeywordFilter>("TOP2 (통합)"), [device,setDevice]=useState<DeviceFilter>("ALL"), [month,setMonth]=useState("2026-09"), [timeFilter,setTimeFilter]=useState<TimeFilter>("ALL");
  const [includeWeekend,setIncludeWeekend]=useState(false), [compareHourly,setCompareHourly]=useState(false), [compareWeekend,setCompareWeekend]=useState(false), [focused,setFocused]=useState<string|null>(null), [modal,setModal]=useState(false);
  useEffect(()=>{ fetch(`${import.meta.env.BASE_URL}data/latest.json`,{cache:"no-store"}).then(r=>{if(!r.ok)throw 0;return r.json()}).then(p=>{if(p.observations?.length){setObservations(p.observations);setGeneratedAt(p.generatedAt??null)}}).catch(()=>undefined) },[]);
  const months=useMemo(()=>availableMonths(observations),[observations]);
  useEffect(()=>{if(months.length&&!months.includes(month))setMonth(months.at(-1)!)},[months,month]);
  const base=useMemo(()=>observations.filter(r=>keywordsFor(keyword).includes(r.keyword as never)&&(device==="ALL"||r.device===device)),[observations,keyword,device]);
  const monthRows=useMemo(()=>base.filter(r=>kst(r.observedAt).month===month),[base,month]);
  const chartRows=useMemo(()=>monthRows.filter(r=>{const p=kst(r.observedAt), seg=TIME_SEGMENTS.find(s=>s.id===timeFilter);return(includeWeekend||!["Sat","Sun"].includes(p.weekday))&&(!seg||seg.hours.includes(p.hour as never))}),[monthRows,includeWeekend,timeFilter]);
  const visible=focused?chartRows.filter(r=>r.company===focused):chartRows, summaries=sortedCompanies(chartRows), previous=base.filter(r=>kst(r.observedAt).month===prevMonth(month));
  const daily=useMemo(()=>[...new Set(visible.map(r=>kst(r.observedAt).date))].sort().map(date=>({date:date.slice(5).replace("-","/"),...Object.fromEntries(COMPANIES.map(c=>[c,avg(visible.filter(r=>kst(r.observedAt).date===date&&r.company===c))]))})),[visible]);
  const detail=useMemo(()=>[...new Set(chartRows.map(r=>kst(r.observedAt).date))].sort().map(date=>({date,values:Object.fromEntries(COMPANIES.map(c=>[c,avg(chartRows.filter(r=>kst(r.observedAt).date===date&&r.company===c))]))})),[chartRows]);
  const weeks=useMemo(()=>{const m=new Map<string,RankingObservation[]>();chartRows.forEach(r=>{const key=`${Math.ceil(Number(kst(r.observedAt).date.slice(-2))/7)}주차`;m.set(key,[...(m.get(key)??[]),r])});return[...m].map(([label,rows])=>({label,rows}))},[chartRows]);
  const previousWeekRows=useMemo(()=>{if(weeks.length>1)return weeks.at(-2)!.rows;const dates=[...new Set(previous.map(r=>kst(r.observedAt).date))].sort().slice(-7);return previous.filter(r=>dates.includes(kst(r.observedAt).date))},[weeks,previous]);
  const hourly=useMemo(()=>TIME_SEGMENTS.map(s=>({...s,values:Object.fromEntries(COMPANIES.map(c=>[c,avg(monthRows.filter(r=>r.company===c&&s.hours.includes(kst(r.observedAt).hour as never)))]))})),[monthRows]);
  const prevHourly=useMemo(()=>TIME_SEGMENTS.map(s=>({...s,values:Object.fromEntries(COMPANIES.map(c=>[c,avg(previous.filter(r=>r.company===c&&s.hours.includes(kst(r.observedAt).hour as never)))]))})),[previous]);
  const weekend=useMemo(()=>COMPANIES.map(company=>{const rows=monthRows.filter(r=>r.company===company),weekday=avg(rows.filter(r=>!["Sat","Sun"].includes(kst(r.observedAt).weekday))),weekend=avg(rows.filter(r=>["Sat","Sun"].includes(kst(r.observedAt).weekday)));return{company,weekday,weekend,diff:weekday!=null&&weekend!=null?weekend-weekday:null}}).filter(r=>r.weekday!=null||r.weekend!=null),[monthRows]);
  const companyInsights=useMemo(()=>COMPANIES.map(company=>{
    const rows=chartRows.filter(r=>r.company===company), overall=avg(rows);
    const segments=TIME_SEGMENTS.flatMap(s=>{const value=avg(rows.filter(r=>s.hours.includes(kst(r.observedAt).hour as never)));return value==null?[]:[{label:s.label,value}]}).sort((a,b)=>a.value-b.value);
    if(overall==null)return null;
    const business=avg(rows.filter(r=>{const h=kst(r.observedAt).hour;return h>=9&&h<=17})),off=avg(rows.filter(r=>{const h=kst(r.observedAt).hour;return h<9||h>17}));
    const lead=segments[0],tail=segments.at(-1),segmentGap=lead&&tail?tail.value-lead.value:0,scheduleGap=business!=null&&off!=null?business-off:0;
    let status="안정적 운영",tone="stable",description=`시간대별 편차 없이 일정한 입찰 강도를 유지하고 있습니다.`;
    if(overall<=1.7){status="시장 지배";tone="leader";description=`전체 평균 ${overall.toFixed(1)}위로 최상위권을 수성하며 시간대 전반에서 공격적인 입찰 우위를 유지하고 있습니다.`}
    else if(overall>=5&&off!=null&&business!=null&&off<business-.4){status="심야 틈 공략";tone="night";description=`업무시간(평균 ${business.toFixed(1)}위)보다 비업무시간(평균 ${off.toFixed(1)}위)에 더 높은 순위를 기록하며, 경쟁이 완화되는 구간에서 노출 효율을 높이고 있습니다.`}
    else if(overall>=5){status="하위권 체류";tone="weak";description=`전체 평균 ${overall.toFixed(1)}위로 하위권에 머물고 있으며, ${lead?`${lead.label}(평균 ${lead.value.toFixed(1)}위)`:"우위 시간대"} 중심의 선택적 순위 개선이 필요합니다.`}
    else if(business!=null&&off!=null&&scheduleGap<-.4){status="업무시간 집중";tone="focus";description=`업무시간(평균 ${business.toFixed(1)}위)에 집중하고 비업무시간(평균 ${off.toFixed(1)}위)에는 예산을 축소하는 선택과 집중 전략을 구사 중입니다.`}
    else if(business!=null&&off!=null&&scheduleGap>.4){status="비업무시간 공략";tone="night";description=`업무시간(평균 ${business.toFixed(1)}위)보다 비업무시간(평균 ${off.toFixed(1)}위)에 더 높은 순위를 기록하며, 비경쟁 시간대 노출을 강화하고 있습니다.`}
    else if(segmentGap>=1.2&&lead&&tail){status="시간대 선택 운영";tone="focus";description=`${lead.label}(평균 ${lead.value.toFixed(1)}위)에 집중하고 ${tail.label}(평균 ${tail.value.toFixed(1)}위)에는 순위를 낮춰 예산 효율화를 추진 중입니다.`}
    return{company,overall,business,off,status,tone,description};
  }).filter(v=>v!=null),[chartRows]);
  const monthlyChanges=useMemo(()=>COMPANIES.flatMap(company=>{const cur=avg(chartRows.filter(r=>r.company===company)),pre=avg(previous.filter(r=>r.company===company));if(cur==null||pre==null)return[];const change=cur-pre;return Math.abs(change)<.1?[]:[{company,change,text:`전월 대비 평균 ${Math.abs(change).toFixed(1)}위 ${change<0?"상승(강세)":"하락(약세)"}.`}]}),[chartRows,previous]);
  const best=summaries[0], second=summaries[1], worst=summaries.at(-1),leadGap=best&&second?second.average!-best.average!:0, insight=best?`${best.company} ${leadGap>=.7?"독주 체제":"선두 경쟁"} 하에, 중위권 업체들의 순위 다툼이 치열합니다. 선두는 관측 평균 ${best.average!.toFixed(1)}위이며 ${worst?.company??"하위 업체"} 대비 ${((worst?.average??best.average!)-best.average!).toFixed(1)}위 앞서 있습니다.`:"선택 조건에 수집된 데이터가 없습니다.";
  return <div className="dashboard-container"><div className="ambient blue"/><div className="ambient indigo"/><div className="ambient sky"/>
    <header className="top-shell"><section className="hero-card"><span className="pill"><Sparkles/> AI RANKING INTELLIGENCE</span><h1>타사 순위 분석 솔루션 (AI)</h1><p>최근 타사들의 순위 입찰 전략과 점유율 변화, 운영 특이사항을 AI가 파악합니다.</p><span className="status"><i/>{generatedAt?`전일 확정 · ${new Date(generatedAt).toLocaleString("ko-KR",{timeZone:"Asia/Seoul"})}`:"공개 데모 데이터"}</span></section>
    <section className="control-card"><div className="control-row keyword-row"><Label icon={<Tag/>}>Keyword</Label><Segments items={keywordButtons.map(v=>[v.value,v.label])} value={keyword} set={v=>setKeyword(v as KeywordFilter)}/><button className="detail-button" onClick={()=>setModal(true)}><List/>24H 상세 랭킹보드</button></div><div className="control-row"><Label icon={<Monitor/>}>Device</Label><Segments items={[["ALL","통합"],["PC","PC"],["MOBILE","Mobile"]]} value={device} set={v=>setDevice(v as DeviceFilter)}/><Label icon={<CalendarDays/>}>Month</Label><Segments items={months.map(v=>[v,v])} value={month} set={setMonth}/></div>{focused&&<button className="focus-chip" onClick={()=>setFocused(null)}><i/>{focused} 집중 분석 모드 (Click to Reset)</button>}</section></header>
    <main className="report-shell"><Card title="AI 운영 전략 및 패턴 분석 리포트 (선택 키워드 기준)" icon={<Bot/>}><div className="insight"><b>• [{keyword}] 시장 경쟁 상황</b><p>{insight}</p><div className="insight-list">{companyInsights.map(v=><div key={v.company}><strong style={{color:COMPANY_COLORS[v.company]}}>{v.company}</strong><span className={`strategy-tag ${v.tone}`}>{v.status}</span><p>{v.description}</p></div>)}</div><p>• 현재 기준: <strong>{keyword}</strong> · <strong>{device==="ALL"?"통합":device}</strong> · <strong>{month}</strong></p><p>• 평균순위는 정해진 시간마다 정상 수집된 네이버 검색광고 노출 결과의 관측 평균이며, 경쟁사의 실제 광고 노출수를 의미하지 않습니다.</p></div></Card>
    <Card title="일자별 관측 평균순위 흐름 (선택 월)" action={<Toggle label="주말 포함" value={includeWeekend} set={setIncludeWeekend}/>}><TimeButtons value={timeFilter} set={setTimeFilter}/><div className="chart-area"><ResponsiveContainer width="100%" height={400}><LineChart data={daily}><CartesianGrid stroke="#e8edf4" vertical={false}/><XAxis dataKey="date"/><YAxis reversed domain={[1,10]} ticks={[1,2,3,4,5,6,7,8,9,10]}/><Tooltip formatter={v=>rank(Number(v))}/>{(focused?[focused]:COMPANIES).map(c=><Line key={c} dataKey={c} type="monotone" stroke={COMPANY_COLORS[c]} strokeWidth={2.4} dot={{r:2}} connectNulls/>)}</LineChart></ResponsiveContainer></div><div className="subheading"><span><BarChart3/>일자별 상세 데이터</span><small>Tip: 업체명을 클릭하면 전체 대시보드가 필터링됩니다.</small><button className="excel" onClick={()=>excel(`${month}_일자별순위.xls`,["날짜",...COMPANIES],detail.map(r=>[r.date,...COMPANIES.map(c=>rank(r.values[c]))]))}><Download/>Excel 저장</button></div><div className="table-scroll daily"><table className="pro-table"><thead><tr><th>날짜</th>{COMPANIES.map(c=><th key={c}><Company name={c} set={setFocused}/></th>)}</tr></thead><tbody>{detail.map(r=><tr key={r.date}><td>{r.date}</td>{COMPANIES.map(c=><td key={c}>{rank(r.values[c])}</td>)}</tr>)}</tbody></table></div></Card>
    <Card title="주차별 및 월별 평균 순위 통합 분석"><div className="table-scroll"><table className="pro-table"><thead><tr><th>업체명</th><th className="prev-average">{Number(prevMonth(month).slice(5))}월 전체평균</th>{weeks.map(w=><th key={w.label}>{Number(month.slice(5))}월 {w.label}</th>)}<th className="current-average">{Number(month.slice(5))}월 전체평균</th><th>WoW (전주 比)</th><th>MoM (전월 比)</th></tr></thead><tbody>{COMPANIES.map(c=>{const companyRows=chartRows.filter(r=>r.company===c),cur=avg(companyRows),pre=avg(previous.filter(r=>r.company===c)),wv=weeks.map(w=>avg(w.rows.filter(r=>r.company===c))),currentWeek=wv.at(-1)??null,priorWeek=avg(previousWeekRows.filter(r=>r.company===c)),wow=currentWeek!=null&&priorWeek!=null?currentWeek-priorWeek:null;return <tr key={c}><td><Company name={c} set={setFocused}/></td><td className="prev-average">{rank(pre)}</td>{wv.map((v,i)=><td key={i}>{rank(v)}</td>)}<td className="current-average">{rank(cur)}</td><td><Diff value={wow}/></td><td><Diff value={cur!=null&&pre!=null?cur-pre:null}/></td></tr>})}</tbody></table></div><Analysis title="Weekly & Monthly Strategy Insight"><div className="analysis-lines"><p><strong style={{color:best?COMPANY_COLORS[best.company]:undefined}}>{best?.company??"-"}</strong>: 선택 월 관측 평균 선두입니다.</p>{monthlyChanges.length?monthlyChanges.map(v=><p key={v.company}><strong style={{color:COMPANY_COLORS[v.company]}}>{v.company}</strong>: {v.text}</p>):<p>전월 비교 데이터가 쌓이면 변화 분석이 자동 생성됩니다.</p>}</div></Analysis></Card>
    <Card title="시간대별 플레이 분석 (Time Segments)" action={<Toggle label="지난달과 비교하기" value={compareHourly} set={setCompareHourly}/>}><div className="legend"><i className="best"/> 해당 시간대 1위 (Best)<i className="worst"/> 최하위(열위)</div><div className="table-scroll"><table className="pro-table"><thead><tr><th>업체명</th>{TIME_SEGMENTS.map(s=><th key={s.id}>{s.label}<small>{String(s.hours[0]).padStart(2,"0")}–{String(s.hours.at(-1)).padStart(2,"0")}시</small></th>)}</tr></thead><tbody>{COMPANIES.map(c=><tr key={c}><td><Company name={c} set={setFocused}/></td>{hourly.map((s,i)=>{const v=s.values[c],nums=Object.values(s.values).filter((n):n is number=>n!=null),cls=v!=null&&v===Math.min(...nums)?"best-cell":v!=null&&v===Math.max(...nums)?"worst-cell":"",pv=prevHourly[i].values[c];return <td className={cls} key={s.id}>{rank(v)}{compareHourly&&<small><Diff value={v!=null&&pv!=null?v-pv:null}/></small>}</td>})}</tr>)}</tbody></table></div><Analysis title="Hourly Operation Pattern Insight"><div className="analysis-lines">{monthlyChanges.length>0&&<><small>[전월 대비 변동]</small>{monthlyChanges.map(v=><p key={v.company}><strong style={{color:COMPANY_COLORS[v.company]}}>{v.company}</strong>: {v.text}</p>)}<hr/></>}{companyInsights.map(v=><p key={v.company}><strong style={{color:COMPANY_COLORS[v.company]}}>{v.company}</strong>: {v.description}</p>)}</div></Analysis></Card>
    <Card title="평일 vs 주말 운영 비교" action={<Toggle label="지난달과 비교하기" value={compareWeekend} set={setCompareWeekend}/>}><div className="table-scroll"><table className="pro-table"><thead><tr><th>업체명</th><th>평일(월~금)</th><th>주말(토,일)</th><th>차이</th><th>운영 패턴</th></tr></thead><tbody>{weekend.map(r=><tr key={r.company}><td><Company name={r.company} set={setFocused}/></td><td>{rank(r.weekday)}</td><td>{rank(r.weekend)}</td><td><Diff value={r.diff}/></td><td>{r.diff==null?"비교 데이터 부족":Math.abs(r.diff)<.3?"유사 운영":r.diff<0?"주말 강화":"평일 강화"}{compareWeekend&&" · 전월 비교"}</td></tr>)}</tbody></table></div></Card></main>
    <footer><p>무단 전재 및 재배포 금지 (Do not reproduce or distribute without permission)</p><b>MINDKNOCK</b></footer>{modal&&<Modal rows={observations} initialMonth={month} close={()=>setModal(false)}/>}</div>;
}

function Label({icon,children}:{icon:React.ReactNode;children:React.ReactNode}){return <span className="control-label">{icon}{children}</span>}
function Segments({items,value,set}:{items:(string[])[];value:string;set:(v:string)=>void}){return <div className="segments">{items.map(([v,l])=><button className={`${value===v?"active ":""}${COMPANY_COLORS[v]?"company-segment":""}`} style={COMPANY_COLORS[v]?{color:COMPANY_COLORS[v],borderColor:COMPANY_COLORS[v]}:undefined} onClick={()=>set(v)} key={v}>{l}</button>)}</div>}
function Card({title,icon,action,children}:{title:string;icon?:React.ReactNode;action?:React.ReactNode;children:React.ReactNode}){return <section className="card"><header><h3>{icon}{title}</h3>{action}</header><div className="card-body">{children}</div></section>}
function Toggle({label,value,set}:{label:string;value:boolean;set:(v:boolean)=>void}){return <label className="toggle-label"><button role="switch" aria-checked={value} className={`toggle ${value?"on":""}`} onClick={()=>set(!value)}><i/></button>{label}</label>}
function TimeButtons({value,set}:{value:TimeFilter;set:(v:TimeFilter)=>void}){return <div className="time-buttons"><button className={value==="ALL"?"active":""} onClick={()=>set("ALL")}>전체 시간대</button>{TIME_SEGMENTS.map(s=><button className={value===s.id?"active":""} onClick={()=>set(s.id)} key={s.id}>{s.label}</button>)}</div>}
function Company({name,set}:{name:string;set:(v:string)=>void}){return <button className="company" style={{color:COMPANY_COLORS[name]}} onClick={()=>set(name)}>{name}</button>}
function Diff({value}:{value:number|null}){return value==null?<span className="muted">-</span>:<span className={`diff ${value<=0?"good":"bad"}`}>{value<0?`+${Math.abs(value).toFixed(1)}`:value>0?`△${value.toFixed(1)}`:"0.0"}</span>}
function Analysis({title,children}:{title:string;children:React.ReactNode}){return <div className="analysis"><b>{title}</b><div className="analysis-content">{children}</div></div>}
function Modal({rows,initialMonth,close}:{rows:RankingObservation[];initialMonth:string;close:()=>void}){
  const months=availableMonths(rows), [keyword,setKeyword]=useState<(typeof KEYWORDS)[number]>(KEYWORDS[0]), [device,setDevice]=useState<DeviceFilter>("ALL"), [month,setMonth]=useState(initialMonth), [company,setCompany]=useState<(typeof COMPANIES)[number]>(COMPANIES[0]);
  const monthDates=[...new Set(rows.filter(r=>kst(r.observedAt).month===month).map(r=>kst(r.observedAt).date))].sort(), [start,setStart]=useState(monthDates[0]??""), [end,setEnd]=useState(monthDates.at(-1)??"");
  useEffect(()=>{const ds=[...new Set(rows.filter(r=>kst(r.observedAt).month===month).map(r=>kst(r.observedAt).date))].sort();setStart(ds[0]??"");setEnd(ds.at(-1)??"")},[month,rows]);
  const scope=rows.filter(r=>r.keyword===keyword&&(device==="ALL"||r.device===device)&&kst(r.observedAt).month===month&&(!start||kst(r.observedAt).date>=start)&&(!end||kst(r.observedAt).date<=end)), companyRows=scope.filter(r=>r.company===company), dates=[...new Set(scope.map(r=>kst(r.observedAt).date))].sort();
  const value=(date:string,hours:number[])=>avg(companyRows.filter(r=>kst(r.observedAt).date===date&&hours.includes(kst(r.observedAt).hour)));
  const boardRank=(value:number|null)=>value==null?"-":value.toFixed(1);
  const weekday=(date:string)=>new Intl.DateTimeFormat("ko-KR",{timeZone:"Asia/Seoul",weekday:"short"}).format(new Date(`${date}T12:00:00+09:00`));
  return <div className="modal-bg" onMouseDown={e=>e.target===e.currentTarget&&close()}><section className="modal"><header><h3><List/>24H 상세 랭킹 보드</h3><div><button className="excel green" onClick={()=>excel(`${month}_24H상세순위.xls`,["시간","키워드","디바이스","업체","순위","네이버페이"],scope.map(r=>[new Date(r.observedAt).toLocaleString("ko-KR",{timeZone:"Asia/Seoul"}),r.keyword,r.device,r.company,r.rank??"-",r.naverPay?"Y":"N"]))}><Download/>Excel 저장 (전체 업체)</button><button className="close" aria-label="닫기" onClick={close}><X/></button></div></header><div className="modal-filter"><Label icon={<Tag/>}>Keyword</Label><Segments items={KEYWORDS.map(v=>[v,v])} value={keyword} set={v=>setKeyword(v as typeof keyword)}/><Label icon={<Monitor/>}>Device</Label><Segments items={[["ALL","통합"],["PC","PC"],["MOBILE","Mobile"]]} value={device} set={v=>setDevice(v as DeviceFilter)}/><Label icon={<CalendarDays/>}>Date</Label><div className="date-range"><input aria-label="시작일" type="date" value={start} min={monthDates[0]} max={end||monthDates.at(-1)} onChange={e=>setStart(e.target.value)}/><span>~</span><input aria-label="종료일" type="date" value={end} min={start||monthDates[0]} max={monthDates.at(-1)} onChange={e=>setEnd(e.target.value)}/></div><Label icon={<CalendarDays/>}>Month</Label><Segments items={months.map(v=>[v,v])} value={month} set={setMonth}/></div><div className="modal-company-tabs"><Segments items={COMPANIES.map(v=>[v,v])} value={company} set={v=>setCompany(v as typeof company)}/></div><div className="modal-table"><table className="pro-table rank-board"><thead><tr><th>시간 \ 일자</th>{dates.map(d=><th key={d}>{d.slice(5)}<small>({weekday(d)})</small></th>)}</tr></thead><tbody><tr className="work-summary"><th>업무시간 평균<small>(09~17시)</small></th>{dates.map(d=><td key={d}>{boardRank(value(d,[9,10,11,12,13,14,15,16,17]))}</td>)}</tr><tr className="off-summary"><th>비업무시간 평균<small>(18~08시)</small></th>{dates.map(d=><td key={d}>{boardRank(value(d,[18,19,20,21,22,23,0,1,2,3,4,5,6,7,8]))}</td>)}</tr>{Array.from({length:24},(_,h)=><tr className={h>=9&&h<=17?"work-hour":""} key={h}><th>{String(h).padStart(2,"0")}시</th>{dates.map(d=><td key={d}>{boardRank(value(d,[h]))}</td>)}</tr>)}</tbody></table></div></section></div>}
